env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 1
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  eqeqeq:
    - error
    - always
  no-else-return:
    - error
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  curly:
    - error
    - all
