env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 1
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
